contact_links:
  - name: ğŸ’¬ è­°è«–ã™ã‚‹(Start discussion)
    url: https://github.com/yojo-art/cherrypick/discussions
    about: è­°è«–ã‚„è³ªå•ã¯ã“ã¡ã‚‰ã¸(The official forum to join conversation and ask question)
